### ISSUE TITLE
App crash due to java.lang.ArrayIndexOutOfBoundsException: length=3; index=3

### ISSUE THREAD

**Issue by manishpatelgt** [theeasiestway/android-opus-codec#2]
Here is the logs

```
2020-06-11 12:38:40.335 14318-14318/com.theeasiestway.opus E/easiestway.opu: [qarth_debug:]  get PatchStore::createDisableExceptionQarthFile method fail.
2020-06-11 12:38:40.340 14318-14318/com.theeasiestway.opus E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.theeasiestway.opus, PID: 14318
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=123, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.theeasiestway.opus/com.theeasiestway.opusapp.MainActivity}: java.lang.ArrayIndexOutOfBoundsException: length=3; index=3
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5078)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5120)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
     Caused by: java.lang.ArrayIndexOutOfBoundsException: length=3; index=3
        at com.theeasiestway.opusapp.MainActivity.onRequestPermissionsResult(MainActivity.kt:208)
```

Just reported

**Comment by theeasiestway** [comment]
@manishpatelgt Thanks for the report! I fixed it just now and pushed to develop branch.

**Comment by manishpatelgt** [comment]
@theeasiestway  Great thanks !!!
